name: build-and-push
on: [push,workflow_dispatch]
env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: oplui
          containerfiles: |
            ./Containerfile

      - name: Login to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Push image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/opdev

      - name: Update Deployment
        id: update-deployment
        uses: redhat-actions/oc-login@v1
        with:
          insecure_skip_tls_verify: true
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_ACCOUNT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Patch deployment
        id: patch-deployment
        env:
          IMAGE_DIGEST: ${{ steps.push-image.outputs.digest }}
        run: |
          oc patch deployment ui -p '{"spec":{"template":{"spec":{"containers":[{"name":"ui","image":"quay.io/opdev/oplui@'${IMAGE_DIGEST}'"}]}}}}'

      - name: Print image URL
        run: echo "Built, pushed, and deployed successfully."
